---
- include: tlp.yml

- name: Copy logind configuration file
  copy: src=logind.conf dest=/etc/systemd/logind.conf

- name: Install powertop
  pacman: name=powertop state=present

- name: Install powerstat
  aur: name=powerstat-git user={{ user.name }}
  tags:
    - aur

- name: Install battery-stats
  aur:
    name: battery-stats-git
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install battop
  aur:
    name: battop
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install network-manager-applet
  pacman: name=network-manager-applet state=present

- name: Install redshift
  pacman: name=redshift state=present
