---
- name: Install acpi_call for TLP battery functions
  pacman: name=acpi_call-dkms state=present
  tags:
    - battery

- name: Install fprintd
  pacman: name=fprintd state=present
  tags:
    - fingerprint

- name: Push sudo authentication file
  template: src=pam.d/sudo.j2 dest=/etc/pam.d/sudo
  tags:
    - fingerprint

- name: Push i3lock authentication file
  template: src=pam.d/i3lock.j2 dest=/etc/pam.d/i3lock
  tags:
    - fingerprint

- name: Install fingerprint-gui
  aur:
    name: fingerprint-gui
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - fingerprint-gui
    - fingerprint
    - aur

- name: Add '{{ user.name }}' to the 'plugdev and scanner' groups
  user:
    name: '{{ user.name }}'
    groups:
      - plugdev
      - scanner
    append: yes

# - name: Push trackpoint udev rules
#   copy: src=10-trackpoint.rules dest=/etc/udev/rules.d/10-trackpoint.rules
#   tags:
#     - trackpoint
