---
- name: Install Bash
  pacman:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install ZSH
  pacman:
    name:
      - zsh
      - zsh-completions
    state: present
  tags:
    - shell

- name: Install Tilda
  pacman:
    name:
      - tilda
    state: present
  tags:
    - terminal

- name: Install screenfetch
  pacman:
    name:
      - screenfetch
    state: present
  tags:
    - terminal
    - screenfetch

- name: Install powerline-fonts
  pacman:
    name:
      - powerline-fonts
    state: present
  tags:
    - fonts

